image: golang:latest

before_script:
  - go get -u golang.org/x/vgo
  - apt-get update
  - apt-get install -y ruby-sass
  - curl https://sh.rustup.rs -sSf | sh -s -- -y


stages:
    - build
    - test

build:
    stage: build
    script:
      - make build
      - cp install/vidocq /usr/bin/vidocq
    artifacts:
      paths:
        - flemzerd

test:
    stage: test
    script:
      - vgo vet ./...
      - make test
