image: golang:latest

cache:
    paths:
        - server/ui/node_modules
        - install/vidocq

before_script:
  - go get -u golang.org/x/vgo
  - apt-get update
  - apt-get install -y curl gcc g++ make
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=~/.cargo/bin:$PATH

stages:
    - test
    - build

test:
    stage: test
    script:
      - make install/vidocq
      - cp install/vidocq /usr/bin/vidocq
      - vgo vet ./...
      - make test

build:
    stage: build
    script:
      - make build
    artifacts:
      paths:
        - flemzerd
